#!/usr/bin/env python3
"""Regenerate the legacy-slug 301 block inside .htaccess from tools/slugs.py.

English, French and Italian pages used to sit on the Spanish filename
(/en/que-tratamos.html and so on). Task 4.1 moved them onto localised slugs,
so every old path needs a permanent redirect to its new home. Those rules are
derived from the slug map rather than hand-written, so adding or renaming a
page means editing slugs.py and re-running:

    python3 tools/build-htaccess.py

Only the region between the two marker comments is touched.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import slugs as S  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HTACCESS = os.path.join(ROOT, ".htaccess")
BEGIN = "# BEGIN legacy-slug redirects (generated by tools/build-htaccess.py)"
END = "# END legacy-slug redirects"


def rules():
    out = [BEGIN,
           "# Task 4.1 moved EN/FR/IT off the Spanish filenames. Keep these"
           " permanently:",
           "# old inbound links and anything still in the index rely on them."]
    for lang in S.LANGS:
        if lang == "es":
            continue                      # Spanish slugs never moved
        emitted = []
        for key in S.SLUGS:
            if key in S.CONDITION_KEYS:
                continue                  # born localised; no legacy path exists
            old = S.slug(key, "es")
            new = S.slug(key, lang)
            if old == new:
                continue                  # slug is identical in this language
            # A new page must never claim a path an old page still redirects
            # away from, or the redirect would shadow the live page.
            if old in [S.slug(k, lang) for k in S.SLUGS]:
                raise SystemExit(
                    "collision: /%s/%s is both a legacy path and a live page"
                    % (lang, old))
            emitted.append("RewriteRule ^%s/%s$ /%s/%s [R=301,L]"
                           % (lang, old.replace(".", r"\."), lang, new))
        if emitted:
            out.append("")
            out.append("# %s" % lang)
            out.extend(sorted(emitted))
    out.append(END)
    return "\n".join(out)


def main():
    text = open(HTACCESS, encoding="utf-8").read()
    block = rules()
    if BEGIN in text and END in text:
        head = text.split(BEGIN)[0]
        tail = text.split(END)[1]
        text = head + block + tail
    else:
        raise SystemExit("markers not found in .htaccess — add them first")
    open(HTACCESS, "w", encoding="utf-8").write(text)
    print("wrote %d redirect rules" % block.count("RewriteRule"))


if __name__ == "__main__":
    main()
